[package]
name = "gitdb"
version = "0.1.1"
authors = ["David Rusu <davidrusu@protonmail.com>"]
description = "encrypted database built on top of git"
license="GPL-2.0"

[dependencies]
git2 = "0.7.1"
ring = "0.13.0-alpha"
toml = "0.4.5"
serde = "1.0.27"
serde_derive = "1.0.27"
data-encoding = "2.1.1"
time = "0.1.39"
tempfile = "3.0.1"
rmp-serde = "0.13"

# ditto = "0.2.0"
[dependencies.ditto]
path = "../ditto"
